import type { Metadata } from "next";
import "./globals.css";
import { Bangers } from "next/font/google";
import Providers from "./components/providers";
import { Navbar } from "./components/navbar";
import { ReactQueryClientProvider } from "./lib/reactqueryClientProvider";
import { Toaster } from "@/components/ui/toaster";

const bangers = Bangers({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReactQueryClientProvider>
      <html lang="en">
        <body className={`${bangers.className}  antialiased`}>
          <Providers>
            <Navbar />
            <Toaster />
            {children}
          </Providers>
        </body>
      </html>
    </ReactQueryClientProvider>
  );
}
